apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: task-demo-service-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: task-demo
  endpoints:
    - port: http
      path: /metrics
      interval: 15s

